### ISSUE TITLE
Atom Feed

### ISSUE THREAD

**Issue by NicholasTD07** [NicholasTD07/nanoc-blog-site#2]
Ref: https://github.com/nanoc/nanoc/blob/master/lib/nanoc/helpers/blogging.rb

**Gem**

``` ruby
# Gemfile
gem 'builder'
```

**Rules + Template**

```
# atom.haml
= atom_feed :limit => 5
```

**Site Config**

``` yaml
# nanoc.yaml
# Atom Feed
base_url: ""
author_name: ""
author_uri: ""
```

More details in the reference.
